language: python

python:
  -  "2.7"
  -  "3.5"
  
install:
  -  pip install .
  
script: mkdir testàéè && kissanime-dl https://kissanime.to/Anime/Naruto-Shippuuden testàéè --simulate --verbose --openload
